### ISSUE TITLE
project

### ISSUE THREAD

**Issue by MaksymTymkovych** [ciechowoj/calibration#1]
Hi, I'm very interested in this project.
This is multi-camera self calibration based on multiple projections?
This project are based on article of Tomas Svoboda?
It works fine?
http://cmp.felk.cvut.cz/~svoboda/SelfCal/

Thank you for your time.

**Comment by ciechowoj** [comment]
> This is multi-camera self calibration based on multiple projections?

Yes.

> This project are based on article of Tomas Svoboda?

Yes, particularly: Tomas Svoboda, Daniel Martinec, and Tomas Pajdla. A convenient multi-camera self-calibration for virtual environments.

> It works fine?

No, I implemented it for a course at the university, and it isn't exactly the algorithm from the paper. I made a few shortcuts that negatively influenced the robustness of the algorithm (I skipped some steps that increase resistance to noise).

However, it should return meaningful calibration for good enough data.

**Comment by MaksymTymkovych** [comment]
Thanks, I try to understand your code (because original more hard for me).

**Comment by ciechowoj** [comment]
> Thanks, I try to understand your code (because original more hard for me).

There may be differences. I've actually thought that there is no publicity available code at all, until you showed me it yesterday : ).

**Comment by daixiongming** [comment]
Dear ciechowoj,
   Many thanks for your code,could you tell me how to run your code and I have tried many times but many bugs, I appreciate if you can write some steps in the README, could you tell me your email address, I have followed you, and your code are useful to my research. I hope I can contact you when I have some questions. Thanks! My email address is daixiongming@gmail.com

**Comment by ciechowoj** [comment]
The project master can be compiled and run by typing `make run`. You can read the Makefile to get details how to run it by hand. The main binary file `master.bin` shows help, so you can read how to use it there.

The project distortion is abandoned and I'm gonna delete it.

Take a look into 'calibration/main.py', if you want to get know how to use calibration project. I added the description of input data files to README. As I said above the implementation isn't greatest, use at your own risk.

If you are determined enough, you can extract my e-mail address from github data. But at now I'm quite busy with other projects, so do not expect very elaborate responses. You can always ask here, however.

**Comment by daixiongming** [comment]
Many many thanks for your email, this is my second email address banding with daixiongming@gmail.com, my company are doing the project about the multi-camera calibration using wand, the equipment is used for the motion capture in VR games. I have told you our research, maybe you have understood our needs, if you can give us some advice we appreciate,  we all using C++, if your research is good enough ,we could transfer to C++ from python, and from "github issue" I find your reference (http://cmp.felk.cvut.cz/~svoboda/SelfCal/index.html ) about your software, also ,I find the related software from the links, above all, many thanks for your contributions, I am always looking forward to contacting with you . Thanks again.

Realis 3D Game Company
Xiongming Dai
Shenzhen,China

**Comment by ciechowoj** [comment]
Oh, I see now. So, you are certainly on good track, I believe Svoboda's article is good starting point for you. It contains many useful references to papers that explains the details and more basic methods. 

>  I have told you our research, maybe you have understood our needs, if you can give us some advice we appreciate.

I'm very sorry but I'm not an expert in the field and I have some other project at the moment.

> we all using C++, if your research is good enough ,we could transfer to C++ from python

So, I believe you can use it as a starting point, but it isn't even close to something you can use as complete solution. You can consider taking a look at the matlab code http://cmp.felk.cvut.cz/~svoboda/SelfCal associated with the original paper, as it is more complete.

**Comment by daixiongming** [comment]
Many thanks for your reply, but I fail to find the file: master.bin???

**Comment by ciechowoj** [comment]
You need to compile the code first with `make`. And the `master` project is not about camera calibration, it is about raytracing/rendering, so it is hardly useful for your purposes I believe.

**Comment by daixiongming** [comment]
OK ,but the project your said is multi-camera calibration, and I just want to run this , and not raytracing/rendering(I am also interested in this project,but now is calibration, I think raytracing project is useful in the folling research. and we will do motion capture about tracker!!!). could you tell me how to run your calibration software ? and your README have no suggestions about how to use and run!! Many thanks for your time!!.

**Comment by ciechowoj** [comment]
Well I've said it before:

> Take a look into 'calibration/main.py', if you want to get know how to use calibration project. I added the description of input data files to README. As I said above the implementation isn't greatest, use at your own risk.

```
def print_help():
    help = """\
Final project for DIGWOR. Generates files scene.png and view.png which presents recovered scene. Prints recovered intrinsic end extrinsic parameters of cameras.
Usage:
    {0} <input_data.csv> <ground_truth.csv> [<camera_id>]
"""

    print(help.format(os.path.basename(sys.argv[0])))
```

`{0}` is the name of executable. So you should do something like 

```
python3 main.py data/testset_0_0.csv data/testset_0_0.truth.csv 0
```

In the main directory of the project.

**Comment by daixiongming** [comment]
yes ,  many thanks for your reminder， I am so careless, Thanks ! I guess the file should be run by this formats. thanks for your advice . we have complete a version about calibration using wand, and we can compare with you and your reference about the Matlab version. Thanks for your time.
